### ISSUE TITLE
CocoaPods package seems non updated to support Swift 2.2

### ISSUE THREAD

**Issue by ORuban** [yoavlt/LiquidLoader#18]
Using pod installation I had received few unsupported code errors (function "find" as example), that were fixed by using code from current master branch

**Comment by emouawad** [comment]
Same here

**Comment by jerem78** [comment]
Same

**Comment by Gerst20051** [comment]
same problem here 👍 

<img width="559" alt="screenshot 2016-06-25 18 14 31" src="https://cloud.githubusercontent.com/assets/235372/16359387/afd01be6-3b00-11e6-8510-59df413f4a1e.png">

**Comment by mishubaobao** [comment]
same

**Comment by yoavlt** [comment]
Done! 👍

**Comment by Gerst20051** [comment]
sick! @yoavlt
