### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by Tulleb** [yoavlt/LiquidLoader#20]
Hello and thanks for this framework,

Is there a Swift 3 branch on its way?

I can't use it with Xcode 8 and Swift 3 beta and Cocoapods... Or couldn't find how to.

Thanks!

**Comment by lfarah** [comment]
Would also love to see this project working in Xcode 8

**Comment by dudash** [comment]
To get it working with Xcode8 it will at least have to be ported to Swift 2.3 - and you can tell XCode to use legacy swift.  However, you can't mix and match, so I wrote a separate issue to track support for 2.3.  Please see #21
