### ISSUE TITLE
How to use Cocoapods for Swift 2.0

### ISSUE THREAD

**Issue by willowcheng** [yoavlt/LiquidLoader#9]
Hi,

I'm impressive with this effect and found the Swift 2.0 branch which can run the example. However, the current `pod "LiquidLoader"` is not for Swift 2.0. Is there any way I can use it?

**Comment by yoavlt** [comment]
You can specify git branch.

pod "LiquidLoader", :git => 'https://github.com/yoavlt/LiquidLoader.git', :branch => 'swift-2.0'

https://guides.cocoapods.org/using/the-podfile.html
